package com.iwellmass.dispatcher.common.model;

import java.util.Date;

public class DdcRunningTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.TASK_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Integer taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Long executeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Long workflowExecuteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.EXECUTE_BATCH_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private String executeBatchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.WORKFLOW_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Integer workflowId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.DISPATCH_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Date dispatchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.DISPATCH_COUNT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Integer dispatchCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.RECEIVE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Date receiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.START_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.COMPLETE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Date completeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.TIMEOUT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Long timeout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.TIMEOUT_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Date timeoutTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.TIMEOUT_RETRY
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Integer timeoutRetry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_RUNNING_TASK.TIMEOUT_RETRY_TIMES
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	private Integer timeoutRetryTimes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.ID
	 * @return  the value of DDC_RUNNING_TASK.ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.ID
	 * @param id  the value for DDC_RUNNING_TASK.ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.TASK_ID
	 * @return  the value of DDC_RUNNING_TASK.TASK_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Integer getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.TASK_ID
	 * @param taskId  the value for DDC_RUNNING_TASK.TASK_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.EXECUTE_ID
	 * @return  the value of DDC_RUNNING_TASK.EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Long getExecuteId() {
		return executeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.EXECUTE_ID
	 * @param executeId  the value for DDC_RUNNING_TASK.EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setExecuteId(Long executeId) {
		this.executeId = executeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.WORKFLOW_EXECUTE_ID
	 * @return  the value of DDC_RUNNING_TASK.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Long getWorkflowExecuteId() {
		return workflowExecuteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.WORKFLOW_EXECUTE_ID
	 * @param workflowExecuteId  the value for DDC_RUNNING_TASK.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setWorkflowExecuteId(Long workflowExecuteId) {
		this.workflowExecuteId = workflowExecuteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.EXECUTE_BATCH_ID
	 * @return  the value of DDC_RUNNING_TASK.EXECUTE_BATCH_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public String getExecuteBatchId() {
		return executeBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.EXECUTE_BATCH_ID
	 * @param executeBatchId  the value for DDC_RUNNING_TASK.EXECUTE_BATCH_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setExecuteBatchId(String executeBatchId) {
		this.executeBatchId = executeBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.WORKFLOW_ID
	 * @return  the value of DDC_RUNNING_TASK.WORKFLOW_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Integer getWorkflowId() {
		return workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.WORKFLOW_ID
	 * @param workflowId  the value for DDC_RUNNING_TASK.WORKFLOW_ID
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.DISPATCH_TIME
	 * @return  the value of DDC_RUNNING_TASK.DISPATCH_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Date getDispatchTime() {
		return dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.DISPATCH_TIME
	 * @param dispatchTime  the value for DDC_RUNNING_TASK.DISPATCH_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setDispatchTime(Date dispatchTime) {
		this.dispatchTime = dispatchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.DISPATCH_COUNT
	 * @return  the value of DDC_RUNNING_TASK.DISPATCH_COUNT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Integer getDispatchCount() {
		return dispatchCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.DISPATCH_COUNT
	 * @param dispatchCount  the value for DDC_RUNNING_TASK.DISPATCH_COUNT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setDispatchCount(Integer dispatchCount) {
		this.dispatchCount = dispatchCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.RECEIVE_TIME
	 * @return  the value of DDC_RUNNING_TASK.RECEIVE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Date getReceiveTime() {
		return receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.RECEIVE_TIME
	 * @param receiveTime  the value for DDC_RUNNING_TASK.RECEIVE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.START_TIME
	 * @return  the value of DDC_RUNNING_TASK.START_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.START_TIME
	 * @param startTime  the value for DDC_RUNNING_TASK.START_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.COMPLETE_TIME
	 * @return  the value of DDC_RUNNING_TASK.COMPLETE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Date getCompleteTime() {
		return completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.COMPLETE_TIME
	 * @param completeTime  the value for DDC_RUNNING_TASK.COMPLETE_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.TIMEOUT
	 * @return  the value of DDC_RUNNING_TASK.TIMEOUT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Long getTimeout() {
		return timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.TIMEOUT
	 * @param timeout  the value for DDC_RUNNING_TASK.TIMEOUT
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setTimeout(Long timeout) {
		this.timeout = timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.TIMEOUT_TIME
	 * @return  the value of DDC_RUNNING_TASK.TIMEOUT_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Date getTimeoutTime() {
		return timeoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.TIMEOUT_TIME
	 * @param timeoutTime  the value for DDC_RUNNING_TASK.TIMEOUT_TIME
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setTimeoutTime(Date timeoutTime) {
		this.timeoutTime = timeoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.TIMEOUT_RETRY
	 * @return  the value of DDC_RUNNING_TASK.TIMEOUT_RETRY
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Integer getTimeoutRetry() {
		return timeoutRetry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.TIMEOUT_RETRY
	 * @param timeoutRetry  the value for DDC_RUNNING_TASK.TIMEOUT_RETRY
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setTimeoutRetry(Integer timeoutRetry) {
		this.timeoutRetry = timeoutRetry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_RUNNING_TASK.TIMEOUT_RETRY_TIMES
	 * @return  the value of DDC_RUNNING_TASK.TIMEOUT_RETRY_TIMES
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public Integer getTimeoutRetryTimes() {
		return timeoutRetryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_RUNNING_TASK.TIMEOUT_RETRY_TIMES
	 * @param timeoutRetryTimes  the value for DDC_RUNNING_TASK.TIMEOUT_RETRY_TIMES
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	public void setTimeoutRetryTimes(Integer timeoutRetryTimes) {
		this.timeoutRetryTimes = timeoutRetryTimes;
	}
}