package com.iwellmass.dispatcher.common.model;

import java.util.Date;

public class DdcServer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.IP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.PORT
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.LAST_START_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Date lastStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_SERVER.LAST_HB_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Date lastHbTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.ID
	 * @return  the value of DDC_SERVER.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.ID
	 * @param id  the value for DDC_SERVER.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.IP
	 * @return  the value of DDC_SERVER.IP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.IP
	 * @param ip  the value for DDC_SERVER.IP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.PORT
	 * @return  the value of DDC_SERVER.PORT
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.PORT
	 * @param port  the value for DDC_SERVER.PORT
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.STATUS
	 * @return  the value of DDC_SERVER.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.STATUS
	 * @param status  the value for DDC_SERVER.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.LAST_START_TIME
	 * @return  the value of DDC_SERVER.LAST_START_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Date getLastStartTime() {
		return lastStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.LAST_START_TIME
	 * @param lastStartTime  the value for DDC_SERVER.LAST_START_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setLastStartTime(Date lastStartTime) {
		this.lastStartTime = lastStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_SERVER.LAST_HB_TIME
	 * @return  the value of DDC_SERVER.LAST_HB_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Date getLastHbTime() {
		return lastHbTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_SERVER.LAST_HB_TIME
	 * @param lastHbTime  the value for DDC_SERVER.LAST_HB_TIME
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setLastHbTime(Date lastHbTime) {
		this.lastHbTime = lastHbTime;
	}
}