package com.iwellmass.dispatcher.common.model;

import java.util.Date;

public class DdcTaskExecuteStatus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.TASK_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Integer taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Long executeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Long workflowExecuteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_BATCH_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private String executeBatchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Integer workflowId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.MESSAGE
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_TASK_EXECUTE_STATUS.TIMESTAMP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	private Date timestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.ID
	 * @param id  the value for DDC_TASK_EXECUTE_STATUS.ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.TASK_ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.TASK_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Integer getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.TASK_ID
	 * @param taskId  the value for DDC_TASK_EXECUTE_STATUS.TASK_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Long getExecuteId() {
		return executeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_ID
	 * @param executeId  the value for DDC_TASK_EXECUTE_STATUS.EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setExecuteId(Long executeId) {
		this.executeId = executeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_EXECUTE_ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Long getWorkflowExecuteId() {
		return workflowExecuteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_EXECUTE_ID
	 * @param workflowExecuteId  the value for DDC_TASK_EXECUTE_STATUS.WORKFLOW_EXECUTE_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setWorkflowExecuteId(Long workflowExecuteId) {
		this.workflowExecuteId = workflowExecuteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_BATCH_ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.EXECUTE_BATCH_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public String getExecuteBatchId() {
		return executeBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.EXECUTE_BATCH_ID
	 * @param executeBatchId  the value for DDC_TASK_EXECUTE_STATUS.EXECUTE_BATCH_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setExecuteBatchId(String executeBatchId) {
		this.executeBatchId = executeBatchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_ID
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.WORKFLOW_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Integer getWorkflowId() {
		return workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.WORKFLOW_ID
	 * @param workflowId  the value for DDC_TASK_EXECUTE_STATUS.WORKFLOW_ID
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.STATUS
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.STATUS
	 * @param status  the value for DDC_TASK_EXECUTE_STATUS.STATUS
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setStatus(String status) {
		if(status != null && status.length() > 255) {
			status = status.substring(0, 255);
		}
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.MESSAGE
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.MESSAGE
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.MESSAGE
	 * @param message  the value for DDC_TASK_EXECUTE_STATUS.MESSAGE
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setMessage(String message) {
		if(message != null && message.length() > 1024) {
			message = message.substring(0, 1024);
		}
		this.message = message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_TASK_EXECUTE_STATUS.TIMESTAMP
	 * @return  the value of DDC_TASK_EXECUTE_STATUS.TIMESTAMP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_TASK_EXECUTE_STATUS.TIMESTAMP
	 * @param timestamp  the value for DDC_TASK_EXECUTE_STATUS.TIMESTAMP
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}
}