package com.iwellmass.dispatcher.common.model;

import java.util.Date;

public class DdcUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.USER_ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.LOGIN_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.USER_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.USER_PHONE
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.USER_EMAIL
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.CREATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.CREATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.UPDATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DDC_USER.UPDATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.ID
	 * @return  the value of DDC_USER.ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.ID
	 * @param id  the value for DDC_USER.ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.USER_ID
	 * @return  the value of DDC_USER.USER_ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.USER_ID
	 * @param userId  the value for DDC_USER.USER_ID
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.LOGIN_NAME
	 * @return  the value of DDC_USER.LOGIN_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.LOGIN_NAME
	 * @param loginName  the value for DDC_USER.LOGIN_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.USER_NAME
	 * @return  the value of DDC_USER.USER_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.USER_NAME
	 * @param userName  the value for DDC_USER.USER_NAME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.USER_PHONE
	 * @return  the value of DDC_USER.USER_PHONE
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.USER_PHONE
	 * @param userPhone  the value for DDC_USER.USER_PHONE
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.USER_EMAIL
	 * @return  the value of DDC_USER.USER_EMAIL
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.USER_EMAIL
	 * @param userEmail  the value for DDC_USER.USER_EMAIL
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.CREATE_USER
	 * @return  the value of DDC_USER.CREATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.CREATE_USER
	 * @param createUser  the value for DDC_USER.CREATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.CREATE_TIME
	 * @return  the value of DDC_USER.CREATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.CREATE_TIME
	 * @param createTime  the value for DDC_USER.CREATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.UPDATE_USER
	 * @return  the value of DDC_USER.UPDATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.UPDATE_USER
	 * @param updateUser  the value for DDC_USER.UPDATE_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DDC_USER.UPDATE_TIME
	 * @return  the value of DDC_USER.UPDATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DDC_USER.UPDATE_TIME
	 * @param updateTime  the value for DDC_USER.UPDATE_TIME
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}