spring:
  application:
    name: idc
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.iwellmass.com:3306/idc?characterEncoding=utf8
    username: root
    password: zjhz2017
server:
  port: 9306
  
  
spring.jpa.hibernate.ddl-auto: update
# spring.jpa.show-sql: true