stages:
  - maven-build

variables:
  idc_latest: idc:latest

dev maven package build:
  stage: maven-build
  script:
    - mvn clean package -DskipTests
    - docker-compose -f docker-compose-dev.yml build
    - docker-compose -f docker-compose-dev.yml up -d
  tags:
    - manager-runner
  only:
    - dev

test maven package build:
  stage: maven-build
  script:
    - mvn clean package -DskipTests
    - docker-compose -f docker-compose-test.yml build
    - docker-compose -f docker-compose-test.yml up -d
  tags:
    - test-runner
  only:
    - test