stages:
  - maven-build

variables:
  idc_latest: idc:latest

dev maven package build:
  stage: maven-build
  script:
    - echo $CI_PROJECT_DIR
    - mvn clean package -DskipTests -Pprd
    - docker-compose -f docker-compose-dev.yml build
    - docker-compose -f docker-compose-dev.yml up -d
  artifacts:
    name:
        "artifact-idc-server-$CI_PIPELINE_ID"
    paths:
      - idc-app/target/idc-app*.zip
    expire_in:
        15 days
  tags:
    - manager-runner
  only:
    - dev

master maven package build:
  stage: maven-build
  script:
    - echo $CI_PROJECT_DIR
    - mvn clean package -DskipTests -Pprd
    - docker-compose -f docker-compose-test.yml build
    - docker-compose -f docker-compose-test.yml up -d
  artifacts:
    name:
        "artifact-idc-server-$CI_PIPELINE_ID"
    paths:
      - idc-app/target/idc-app*.zip
    expire_in:
        15 days
  tags:
    - test-runner2
  only:
    - test