version: '3'
services:
  idc-server:
    image: $idc_latest
    container_name: idc
    build:
      context: ./idc-admin/idc-admin-web
      args:
        - profile=dev
    network_mode: "host"
    ports:
      - "9306:9306"
    environment:
      - profile=dev
    volumes:
      - /web/logs:/web/logs
networks:
  default:
    external:
      name: mast_nw