ALTER TABLE `ddc`.`DDC_TASK`
  CHANGE `TASK_TYPE` `TASK_TYPE` INT(11) NOT NULL  COMMENT '任务类型（11:定时任务 12:流程子任务 13:简单任务 21:流程任务）',
  ADD COLUMN `SIMPLE_START_TIME` VARCHAR(50) NULL  COMMENT '简单任务执行开始时间' AFTER `NEXT_FIRE_TIME`,
  ADD COLUMN `SIMPLE_END_TIME` VARCHAR(50) NULL  COMMENT '简单任务执行结束时间' AFTER `SIMPLE_START_TIME`,
  ADD COLUMN `SIMPLE_REPEAT_COUNT` INT NULL  COMMENT '简单任务执行重复次数' AFTER `SIMPLE_END_TIME`,
  ADD COLUMN `SIMPLE_REPEAT_INTERVAL` INT NULL  COMMENT '简单任务执行重复间隔' AFTER `SIMPLE_REPEAT_COUNT`;