package com.iwellmass.dispatcher.admin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcAlarmHistory;
import com.iwellmass.dispatcher.admin.dao.model.DdcAlarmHistoryExample;

public interface DdcAlarmHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int countByExample(DdcAlarmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int deleteByExample(DdcAlarmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int insert(DdcAlarmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int insertSelective(DdcAlarmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    List<DdcAlarmHistory> selectByExample(DdcAlarmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    DdcAlarmHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcAlarmHistory record, @Param("example") DdcAlarmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int updateByExample(@Param("record") DdcAlarmHistory record, @Param("example") DdcAlarmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(DdcAlarmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_ALARM_HISTORY
     *
     * @mbggenerated Mon Jul 11 16:23:08 CST 2016
     */
    int updateByPrimaryKey(DdcAlarmHistory record);
}