package com.iwellmass.dispatcher.admin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcHourExecuteStatistic;
import com.iwellmass.dispatcher.admin.dao.model.DdcHourExecuteStatisticExample;
import com.iwellmass.dispatcher.admin.dao.model.DdcHourExecuteStatisticKey;

public interface DdcHourExecuteStatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int countByExample(DdcHourExecuteStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int deleteByExample(DdcHourExecuteStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int deleteByPrimaryKey(DdcHourExecuteStatisticKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int insert(DdcHourExecuteStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int insertSelective(DdcHourExecuteStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    List<DdcHourExecuteStatistic> selectByExample(DdcHourExecuteStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    DdcHourExecuteStatistic selectByPrimaryKey(DdcHourExecuteStatisticKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcHourExecuteStatistic record, @Param("example") DdcHourExecuteStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int updateByExample(@Param("record") DdcHourExecuteStatistic record, @Param("example") DdcHourExecuteStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int updateByPrimaryKeySelective(DdcHourExecuteStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_HOUR_EXECUTE_STATISTIC
     *
     * @mbggenerated Wed Jul 06 11:37:17 CST 2016
     */
    int updateByPrimaryKey(DdcHourExecuteStatistic record);
}