package com.iwellmass.dispatcher.admin.dao.mapper;

import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcSubtaskExecuteHistory;
import com.iwellmass.dispatcher.admin.dao.model.DdcSubtaskExecuteHistoryEx;
import com.iwellmass.dispatcher.admin.dao.model.DdcSubtaskExecuteHistoryExample;

import java.util.List;

public interface DdcSubtaskExecuteHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int countByExample(DdcSubtaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int deleteByExample(DdcSubtaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int deleteByPrimaryKey(Long executeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int insert(DdcSubtaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int insertSelective(DdcSubtaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    List<DdcSubtaskExecuteHistory> selectByExample(DdcSubtaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    DdcSubtaskExecuteHistory selectByPrimaryKey(Long executeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcSubtaskExecuteHistory record, @Param("example") DdcSubtaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int updateByExample(@Param("record") DdcSubtaskExecuteHistory record, @Param("example") DdcSubtaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int updateByPrimaryKeySelective(DdcSubtaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jul 07 15:41:50 CST 2016
     */
    int updateByPrimaryKey(DdcSubtaskExecuteHistory record);

    List<DdcSubtaskExecuteHistoryEx> selectByExampleEx(DdcSubtaskExecuteHistoryEx map);
    int countByExampleEx(DdcSubtaskExecuteHistoryEx map);
}