package com.iwellmass.dispatcher.admin.dao.mapper;

import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcTask;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskExample;

import java.util.List;

public interface DdcTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int countByExample(DdcTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int deleteByExample(DdcTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int insert(DdcTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int insertSelective(DdcTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    List<DdcTask> selectByExample(DdcTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    DdcTask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcTask record, @Param("example") DdcTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByExample(@Param("record") DdcTask record, @Param("example") DdcTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByPrimaryKeySelective(DdcTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByPrimaryKey(DdcTask record);
}