package com.iwellmass.dispatcher.admin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcTaskWorkflow;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskWorkflowExample;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskWorkflowWithBLOBs;

public interface DdcTaskWorkflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int countByExample(DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int deleteByExample(DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int deleteByPrimaryKey(Integer workflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int insert(DdcTaskWorkflowWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int insertSelective(DdcTaskWorkflowWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    List<DdcTaskWorkflowWithBLOBs> selectByExampleWithBLOBs(DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    List<DdcTaskWorkflow> selectByExample(DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    DdcTaskWorkflowWithBLOBs selectByPrimaryKey(Integer workflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcTaskWorkflowWithBLOBs record, @Param("example") DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DdcTaskWorkflowWithBLOBs record, @Param("example") DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByExample(@Param("record") DdcTaskWorkflow record, @Param("example") DdcTaskWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByPrimaryKeySelective(DdcTaskWorkflowWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DdcTaskWorkflowWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_WORKFLOW
     *
     * @mbggenerated Thu May 19 20:40:32 CST 2016
     */
    int updateByPrimaryKey(DdcTaskWorkflow record);
}