package com.iwellmass.dispatcher.admin.dao.mapper;

import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcTaskExecuteHistory;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskExecuteHistoryEx;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskExecuteHistoryExample;

import java.util.List;

public interface DdcTaskExecuteHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int countByExample(DdcTaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int deleteByExample(DdcTaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int deleteByPrimaryKey(Long executeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int insert(DdcTaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int insertSelective(DdcTaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    List<DdcTaskExecuteHistory> selectByExample(DdcTaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    DdcTaskExecuteHistory selectByPrimaryKey(Long executeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcTaskExecuteHistory record, @Param("example") DdcTaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByExample(@Param("record") DdcTaskExecuteHistory record, @Param("example") DdcTaskExecuteHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByPrimaryKeySelective(DdcTaskExecuteHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
     *
     * @mbggenerated Thu Jun 30 13:55:55 CST 2016
     */
    int updateByPrimaryKey(DdcTaskExecuteHistory record);


    List<DdcTaskExecuteHistoryEx> selectByExampleEx(DdcTaskExecuteHistoryEx map);
    int countByExampleEx(DdcTaskExecuteHistoryEx map);
}