package com.iwellmass.dispatcher.admin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcTaskUpdateHistory;
import com.iwellmass.dispatcher.admin.dao.model.DdcTaskUpdateHistoryExample;

public interface DdcTaskUpdateHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int countByExample(DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int deleteByExample(DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int insert(DdcTaskUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int insertSelective(DdcTaskUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    List<DdcTaskUpdateHistory> selectByExampleWithBLOBs(DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    List<DdcTaskUpdateHistory> selectByExample(DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    DdcTaskUpdateHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcTaskUpdateHistory record, @Param("example") DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DdcTaskUpdateHistory record, @Param("example") DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByExample(@Param("record") DdcTaskUpdateHistory record, @Param("example") DdcTaskUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByPrimaryKeySelective(DdcTaskUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DdcTaskUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DDC_TASK_UPDATE_HISTORY
     *
     * @mbggenerated Thu Jul 21 10:34:14 CST 2016
     */
    int updateByPrimaryKey(DdcTaskUpdateHistory record);
}