package com.iwellmass.dispatcher.admin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.admin.dao.model.DdcUserApplication;
import com.iwellmass.dispatcher.admin.dao.model.DdcUserApplicationExample;

public interface DdcUserApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int countByExample(DdcUserApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int deleteByExample(DdcUserApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int insert(DdcUserApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int insertSelective(DdcUserApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    List<DdcUserApplication> selectByExample(DdcUserApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    DdcUserApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") DdcUserApplication record, @Param("example") DdcUserApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int updateByExample(@Param("record") DdcUserApplication record, @Param("example") DdcUserApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int updateByPrimaryKeySelective(DdcUserApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddc_user_application
     *
     * @mbggenerated Wed Jun 22 14:42:56 CST 2016
     */
    int updateByPrimaryKey(DdcUserApplication record);
}