package com.iwellmass.dispatcher.common.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.common.model.DdcRunningTask;
import com.iwellmass.dispatcher.common.model.DdcRunningTaskExample;

public interface DdcRunningTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int countByExample(DdcRunningTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int deleteByExample(DdcRunningTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int insert(DdcRunningTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int insertSelective(DdcRunningTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	List<DdcRunningTask> selectByExample(DdcRunningTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	DdcRunningTask selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DdcRunningTask record,
			@Param("example") DdcRunningTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int updateByExample(@Param("record") DdcRunningTask record, @Param("example") DdcRunningTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int updateByPrimaryKeySelective(DdcRunningTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_RUNNING_TASK
	 * @mbggenerated  Sun Jun 12 15:16:43 CST 2016
	 */
	int updateByPrimaryKey(DdcRunningTask record);
}