package com.iwellmass.dispatcher.common.dao;

import java.util.List;

import com.iwellmass.dispatcher.common.model.DdcSubtaskExecuteHistory;
import com.iwellmass.dispatcher.common.model.DdcSubtaskExecuteHistoryExample;

public interface DdcSubtaskExecuteHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int countByExample(DdcSubtaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int deleteByExample(DdcSubtaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int deleteByPrimaryKey(Long executeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int insert(DdcSubtaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int insertSelective(DdcSubtaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	List<DdcSubtaskExecuteHistory> selectByExample(DdcSubtaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	DdcSubtaskExecuteHistory selectByPrimaryKey(Long executeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DdcSubtaskExecuteHistory record,
			@Param("example") DdcSubtaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int updateByExample(@Param("record") DdcSubtaskExecuteHistory record,
			@Param("example") DdcSubtaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int updateByPrimaryKeySelective(DdcSubtaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_SUBTASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 08 15:30:29 CST 2016
	 */
	int updateByPrimaryKey(DdcSubtaskExecuteHistory record);
}