package com.iwellmass.dispatcher.common.dao;

import java.util.List;

import com.iwellmass.dispatcher.common.model.DdcTaskExecuteHistory;
import com.iwellmass.dispatcher.common.model.DdcTaskExecuteHistoryExample;

public interface DdcTaskExecuteHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int countByExample(DdcTaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int deleteByExample(DdcTaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int deleteByPrimaryKey(Long executeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int insert(DdcTaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int insertSelective(DdcTaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	List<DdcTaskExecuteHistory> selectByExample(DdcTaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	DdcTaskExecuteHistory selectByPrimaryKey(Long executeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DdcTaskExecuteHistory record,
			@Param("example") DdcTaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int updateByExample(@Param("record") DdcTaskExecuteHistory record,
			@Param("example") DdcTaskExecuteHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int updateByPrimaryKeySelective(DdcTaskExecuteHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_TASK_EXECUTE_HISTORY
	 * @mbggenerated  Wed Jun 29 17:23:38 CST 2016
	 */
	int updateByPrimaryKey(DdcTaskExecuteHistory record);

	/**
	 * Acquire DDC_TASK_EXECUTE_HISTORY Lock
	 */
	void acquireWorkflowExecuteLock(@Param("executeId") Long executeId);
}