package com.iwellmass.dispatcher.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.iwellmass.dispatcher.common.model.DdcUser;
import com.iwellmass.dispatcher.common.model.DdcUserAlarm;
import com.iwellmass.dispatcher.common.model.DdcUserExample;

public interface DdcUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int countByExample(DdcUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int deleteByExample(DdcUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int insert(DdcUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int insertSelective(DdcUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	List<DdcUser> selectByExample(DdcUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	DdcUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int updateByExampleSelective(@Param("record") DdcUser record, @Param("example") DdcUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int updateByExample(@Param("record") DdcUser record, @Param("example") DdcUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int updateByPrimaryKeySelective(DdcUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DDC_USER
	 * @mbggenerated  Wed May 04 17:18:42 CST 2016
	 */
	int updateByPrimaryKey(DdcUser record);
	
	/**
	 * 根据DdcUserAlarm中的信息查询满足条件的用户列表
	 * @param record
	 * @return
	 */
	List<DdcUser> selectByUserAlarm(DdcUserAlarm record);
}