spring:
  application:
    name: idc-demo
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
server:
  port: 10086

spring.data.jpa.repositories.enabled: false
spring.cloud.config.enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    status-page-url: "http://eureka.iwellmass.com:${server.port}/swagger-ui.html"
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: "http://eureka.iwellmass.com:8761/eureka/"
    healthcheck:
      enabled: true
    lease:
      duration: 5