ALTER TABLE `DDC_USER_APPLICATION` ADD COLUMN `USER_TYPE` INT NULL  DEFAULT 1  COMMENT '用户类型(1: 普通用户  2: 管理员)' AFTER `USER_ID`;

DROP TABLE IF EXISTS `DDC_USER_ALARM`;

DROP TABLE IF EXISTS `DDC_ALARM_HISTORY`;

CREATE TABLE `DDC_USER_ALARM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `USER_ID` int(11) NOT NULL COMMENT '用户编号',
  `LOGIN_NAME` varchar(50) NOT NULL COMMENT '用户登录名',
  `APP_ID` int(11) NOT NULL COMMENT '应用编号',
  `TASK_ID` int(11) DEFAULT NULL COMMENT '任务编号',
  `CREATE_USER` varchar(50) NOT NULL COMMENT '创建人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `DDC_ALARM_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `APP_ID` int(11) NOT NULL COMMENT '应用编号',
  `TASK_ID` int(11) NOT NULL COMMENT '任务编号',
  `ALARM_KEY` varchar(255) NOT NULL COMMENT '自定义报警点',
  `CONTENT` varchar(1024) DEFAULT NULL COMMENT '报警内容',
  `RECEIVERS` varchar(1024) DEFAULT NULL COMMENT '报警接收人',
  `ALARM_DATE` datetime NOT NULL COMMENT '预警时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

