ALTER TABLE `DDC_TASK_EXECUTE_HISTORY`
  ADD COLUMN `FIRE_TIME` DATETIME NULL  COMMENT '触发时间' AFTER `TRIGGER_TYPE`,
  ADD COLUMN `SHOULD_FIRE_TIME` BIGINT(13) NULL  COMMENT '应启动时间' AFTER `FIRE_TIME`,
  ADD COLUMN `ACTUAL_FIRE_TIME` BIGINT(13) NULL  COMMENT '实际启动时间' AFTER `SHOULD_FIRE_TIME`;
  
ALTER TABLE `DDC_SUBTASK_EXECUTE_HISTORY`
  ADD COLUMN `FIRE_TIME` DATETIME NULL  COMMENT '触发时间' AFTER `TRIGGER_TYPE`,
  ADD COLUMN `SHOULD_FIRE_TIME` BIGINT(13) NULL  COMMENT '应启动时间' AFTER `FIRE_TIME`,
  ADD COLUMN `ACTUAL_FIRE_TIME` BIGINT(13) NULL  COMMENT '实际启动时间' AFTER `SHOULD_FIRE_TIME`;

ALTER TABLE `DDC_TASK`   
  ADD COLUMN `NEXT_FIRE_TIME` DATETIME NULL  COMMENT '下次执行时间' AFTER `LAST_EXECUTE_MESSAGE`;
  
CREATE INDEX IDX_DDC_SUBHISTORY_FIRETIME ON DDC_SUBTASK_EXECUTE_HISTORY
(
   FIRE_TIME
);

CREATE INDEX IDX_DDC_HISTORY_FIRETIME ON DDC_TASK_EXECUTE_HISTORY
(
   FIRE_TIME
);


CREATE TABLE `DDC_FIVE_MINUTE_EXECUTE_STATISTIC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATA_TIME` datetime NOT NULL COMMENT '数据时间戳',
  `APP_ID` int(11) NOT NULL COMMENT '应用编号',
  `TASK_ID` int(11) NOT NULL COMMENT '任务编号',
  `EXECUTE_SUCCEED` int(11) DEFAULT '0' COMMENT '执行成功次数',
  `EXECUTE_FAILED` int(11) DEFAULT '0' COMMENT '执行失败次数',
  `EXECUTE_TIME_OUT` int(11) DEFAULT '0' COMMENT '执行超时次数',
  `EXECUTE_DURATION` double DEFAULT '0' COMMENT '平均执行时间',
  `EXECUTE_MAX_DURATION` double DEFAULT '0' COMMENT '最大执行时间',
  `EXECUTE_MIN_DURATION` double DEFAULT '0' COMMENT '最小执行时间',
  PRIMARY KEY (`ID`,`APP_ID`),
  UNIQUE KEY `UNIQUE_KEY` (`DATA_TIME`,`APP_ID`,`TASK_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `DDC_HOUR_EXECUTE_STATISTIC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DATA_TIME` datetime NOT NULL COMMENT '数据时间戳',
  `APP_ID` int(11) NOT NULL COMMENT '应用编号',
  `TASK_ID` int(11) NOT NULL COMMENT '任务编号',
  `EXECUTE_SUCCEED` int(11) DEFAULT '0' COMMENT '执行成功次数',
  `EXECUTE_FAILED` int(11) DEFAULT '0' COMMENT '执行失败次数',
  `EXECUTE_TIME_OUT` int(11) DEFAULT '0' COMMENT '执行超时次数',
  `EXECUTE_DURATION` double DEFAULT '0' COMMENT '平均执行时间',
  `EXECUTE_MAX_DURATION` double DEFAULT '0' COMMENT '最大执行时间',
  `EXECUTE_MIN_DURATION` double DEFAULT '0' COMMENT '最小执行时间',
  PRIMARY KEY (`ID`,`APP_ID`),
  UNIQUE KEY `UNIQUE_KEY` (`DATA_TIME`,`APP_ID`,`TASK_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


