package com.iwellmass.dispatcher.admin.dao.model;

import java.util.Date;

public class DdcApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.APP_ID
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.APP_KEY
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.APP_NAME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.APP_DESCRIPTION
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private String appDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.APP_STATUS
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private Integer appStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.CREATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.CREATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.UPDATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_APPLICATION.UPDATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.APP_ID
     *
     * @return the value of DDC_APPLICATION.APP_ID
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.APP_ID
     *
     * @param appId the value for DDC_APPLICATION.APP_ID
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.APP_KEY
     *
     * @return the value of DDC_APPLICATION.APP_KEY
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.APP_KEY
     *
     * @param appKey the value for DDC_APPLICATION.APP_KEY
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.APP_NAME
     *
     * @return the value of DDC_APPLICATION.APP_NAME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.APP_NAME
     *
     * @param appName the value for DDC_APPLICATION.APP_NAME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.APP_DESCRIPTION
     *
     * @return the value of DDC_APPLICATION.APP_DESCRIPTION
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public String getAppDescription() {
        return appDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.APP_DESCRIPTION
     *
     * @param appDescription the value for DDC_APPLICATION.APP_DESCRIPTION
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setAppDescription(String appDescription) {
        this.appDescription = appDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.APP_STATUS
     *
     * @return the value of DDC_APPLICATION.APP_STATUS
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public Integer getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.APP_STATUS
     *
     * @param appStatus the value for DDC_APPLICATION.APP_STATUS
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setAppStatus(Integer appStatus) {
        this.appStatus = appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.CREATE_USER
     *
     * @return the value of DDC_APPLICATION.CREATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.CREATE_USER
     *
     * @param createUser the value for DDC_APPLICATION.CREATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.CREATE_TIME
     *
     * @return the value of DDC_APPLICATION.CREATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.CREATE_TIME
     *
     * @param createTime the value for DDC_APPLICATION.CREATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.UPDATE_USER
     *
     * @return the value of DDC_APPLICATION.UPDATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.UPDATE_USER
     *
     * @param updateUser the value for DDC_APPLICATION.UPDATE_USER
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_APPLICATION.UPDATE_TIME
     *
     * @return the value of DDC_APPLICATION.UPDATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_APPLICATION.UPDATE_TIME
     *
     * @param updateTime the value for DDC_APPLICATION.UPDATE_TIME
     *
     * @mbggenerated Tue May 17 10:03:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}