package com.iwellmass.dispatcher.admin.dao.model;

import java.util.Date;

public class DdcTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.APP_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.APP_KEY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_CATEGOTY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer taskCategoty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_IMPLEMENT_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer taskImplementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.CLASS_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.PARAMETERS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String parameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.DATA_LIMIT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer dataLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TIMEOUT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Long timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TIMEOUT_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Boolean timeoutRetry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TIMEOUT_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer timeoutRetryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.FAILED_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Boolean failedRetry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.FAILED_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer failedRetryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.FAILED_RETRY_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Long failedRetryInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.CONCURRENCY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Boolean concurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.MUTITHREAD
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Boolean mutithread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.THREADS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer threads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.TASK_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.CRON
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String cron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.WAIT_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Long waitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.OWNER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.WORKFLOW_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer workflowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.CREATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.CREATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.UPDATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Date lastExecuteStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Date lastExecuteEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_IP
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String lastExecuteIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_PORT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer lastExecutePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_NODE_CODE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String lastExecuteNodeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String lastExecuteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.LAST_EXECUTE_MESSAGE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String lastExecuteMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.NEXT_FIRE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Date nextFireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.SIMPLE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String simpleStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.SIMPLE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private String simpleEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.SIMPLE_REPEAT_COUNT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer simpleRepeatCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DDC_TASK.SIMPLE_REPEAT_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    private Integer simpleRepeatInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_ID
     *
     * @return the value of DDC_TASK.TASK_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_ID
     *
     * @param taskId the value for DDC_TASK.TASK_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_NAME
     *
     * @return the value of DDC_TASK.TASK_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_NAME
     *
     * @param taskName the value for DDC_TASK.TASK_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.APP_ID
     *
     * @return the value of DDC_TASK.APP_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.APP_ID
     *
     * @param appId the value for DDC_TASK.APP_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.APP_KEY
     *
     * @return the value of DDC_TASK.APP_KEY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.APP_KEY
     *
     * @param appKey the value for DDC_TASK.APP_KEY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_CATEGOTY
     *
     * @return the value of DDC_TASK.TASK_CATEGOTY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTaskCategoty() {
        return taskCategoty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_CATEGOTY
     *
     * @param taskCategoty the value for DDC_TASK.TASK_CATEGOTY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskCategoty(Integer taskCategoty) {
        this.taskCategoty = taskCategoty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_TYPE
     *
     * @return the value of DDC_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_TYPE
     *
     * @param taskType the value for DDC_TASK.TASK_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_IMPLEMENT_TYPE
     *
     * @return the value of DDC_TASK.TASK_IMPLEMENT_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTaskImplementType() {
        return taskImplementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_IMPLEMENT_TYPE
     *
     * @param taskImplementType the value for DDC_TASK.TASK_IMPLEMENT_TYPE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskImplementType(Integer taskImplementType) {
        this.taskImplementType = taskImplementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.DESCRIPTION
     *
     * @return the value of DDC_TASK.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.DESCRIPTION
     *
     * @param description the value for DDC_TASK.DESCRIPTION
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.CLASS_NAME
     *
     * @return the value of DDC_TASK.CLASS_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.CLASS_NAME
     *
     * @param className the value for DDC_TASK.CLASS_NAME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.PARAMETERS
     *
     * @return the value of DDC_TASK.PARAMETERS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.PARAMETERS
     *
     * @param parameters the value for DDC_TASK.PARAMETERS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.DATA_LIMIT
     *
     * @return the value of DDC_TASK.DATA_LIMIT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getDataLimit() {
        return dataLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.DATA_LIMIT
     *
     * @param dataLimit the value for DDC_TASK.DATA_LIMIT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setDataLimit(Integer dataLimit) {
        this.dataLimit = dataLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TIMEOUT
     *
     * @return the value of DDC_TASK.TIMEOUT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Long getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TIMEOUT
     *
     * @param timeout the value for DDC_TASK.TIMEOUT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTimeout(Long timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TIMEOUT_RETRY
     *
     * @return the value of DDC_TASK.TIMEOUT_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Boolean getTimeoutRetry() {
        return timeoutRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TIMEOUT_RETRY
     *
     * @param timeoutRetry the value for DDC_TASK.TIMEOUT_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTimeoutRetry(Boolean timeoutRetry) {
        this.timeoutRetry = timeoutRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TIMEOUT_RETRY_TIMES
     *
     * @return the value of DDC_TASK.TIMEOUT_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTimeoutRetryTimes() {
        return timeoutRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TIMEOUT_RETRY_TIMES
     *
     * @param timeoutRetryTimes the value for DDC_TASK.TIMEOUT_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTimeoutRetryTimes(Integer timeoutRetryTimes) {
        this.timeoutRetryTimes = timeoutRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.FAILED_RETRY
     *
     * @return the value of DDC_TASK.FAILED_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Boolean getFailedRetry() {
        return failedRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.FAILED_RETRY
     *
     * @param failedRetry the value for DDC_TASK.FAILED_RETRY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setFailedRetry(Boolean failedRetry) {
        this.failedRetry = failedRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.FAILED_RETRY_TIMES
     *
     * @return the value of DDC_TASK.FAILED_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getFailedRetryTimes() {
        return failedRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.FAILED_RETRY_TIMES
     *
     * @param failedRetryTimes the value for DDC_TASK.FAILED_RETRY_TIMES
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setFailedRetryTimes(Integer failedRetryTimes) {
        this.failedRetryTimes = failedRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.FAILED_RETRY_INTERVAL
     *
     * @return the value of DDC_TASK.FAILED_RETRY_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Long getFailedRetryInterval() {
        return failedRetryInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.FAILED_RETRY_INTERVAL
     *
     * @param failedRetryInterval the value for DDC_TASK.FAILED_RETRY_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setFailedRetryInterval(Long failedRetryInterval) {
        this.failedRetryInterval = failedRetryInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.CONCURRENCY
     *
     * @return the value of DDC_TASK.CONCURRENCY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Boolean getConcurrency() {
        return concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.CONCURRENCY
     *
     * @param concurrency the value for DDC_TASK.CONCURRENCY
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setConcurrency(Boolean concurrency) {
        this.concurrency = concurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.MUTITHREAD
     *
     * @return the value of DDC_TASK.MUTITHREAD
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Boolean getMutithread() {
        return mutithread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.MUTITHREAD
     *
     * @param mutithread the value for DDC_TASK.MUTITHREAD
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setMutithread(Boolean mutithread) {
        this.mutithread = mutithread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.THREADS
     *
     * @return the value of DDC_TASK.THREADS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getThreads() {
        return threads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.THREADS
     *
     * @param threads the value for DDC_TASK.THREADS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setThreads(Integer threads) {
        this.threads = threads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.TASK_STATUS
     *
     * @return the value of DDC_TASK.TASK_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.TASK_STATUS
     *
     * @param taskStatus the value for DDC_TASK.TASK_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.CRON
     *
     * @return the value of DDC_TASK.CRON
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.CRON
     *
     * @param cron the value for DDC_TASK.CRON
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.WAIT_TIME
     *
     * @return the value of DDC_TASK.WAIT_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Long getWaitTime() {
        return waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.WAIT_TIME
     *
     * @param waitTime the value for DDC_TASK.WAIT_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setWaitTime(Long waitTime) {
        this.waitTime = waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.OWNER
     *
     * @return the value of DDC_TASK.OWNER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.OWNER
     *
     * @param owner the value for DDC_TASK.OWNER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.WORKFLOW_ID
     *
     * @return the value of DDC_TASK.WORKFLOW_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.WORKFLOW_ID
     *
     * @param workflowId the value for DDC_TASK.WORKFLOW_ID
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.CREATE_USER
     *
     * @return the value of DDC_TASK.CREATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.CREATE_USER
     *
     * @param createUser the value for DDC_TASK.CREATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.CREATE_TIME
     *
     * @return the value of DDC_TASK.CREATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.CREATE_TIME
     *
     * @param createTime the value for DDC_TASK.CREATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.UPDATE_USER
     *
     * @return the value of DDC_TASK.UPDATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.UPDATE_USER
     *
     * @param updateUser the value for DDC_TASK.UPDATE_USER
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.UPDATE_TIME
     *
     * @return the value of DDC_TASK.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.UPDATE_TIME
     *
     * @param updateTime the value for DDC_TASK.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_START_TIME
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Date getLastExecuteStartTime() {
        return lastExecuteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_START_TIME
     *
     * @param lastExecuteStartTime the value for DDC_TASK.LAST_EXECUTE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteStartTime(Date lastExecuteStartTime) {
        this.lastExecuteStartTime = lastExecuteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_END_TIME
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Date getLastExecuteEndTime() {
        return lastExecuteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_END_TIME
     *
     * @param lastExecuteEndTime the value for DDC_TASK.LAST_EXECUTE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteEndTime(Date lastExecuteEndTime) {
        this.lastExecuteEndTime = lastExecuteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_IP
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_IP
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getLastExecuteIp() {
        return lastExecuteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_IP
     *
     * @param lastExecuteIp the value for DDC_TASK.LAST_EXECUTE_IP
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteIp(String lastExecuteIp) {
        this.lastExecuteIp = lastExecuteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_PORT
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_PORT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getLastExecutePort() {
        return lastExecutePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_PORT
     *
     * @param lastExecutePort the value for DDC_TASK.LAST_EXECUTE_PORT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecutePort(Integer lastExecutePort) {
        this.lastExecutePort = lastExecutePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_NODE_CODE
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_NODE_CODE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getLastExecuteNodeCode() {
        return lastExecuteNodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_NODE_CODE
     *
     * @param lastExecuteNodeCode the value for DDC_TASK.LAST_EXECUTE_NODE_CODE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteNodeCode(String lastExecuteNodeCode) {
        this.lastExecuteNodeCode = lastExecuteNodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_STATUS
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getLastExecuteStatus() {
        return lastExecuteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_STATUS
     *
     * @param lastExecuteStatus the value for DDC_TASK.LAST_EXECUTE_STATUS
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteStatus(String lastExecuteStatus) {
        this.lastExecuteStatus = lastExecuteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.LAST_EXECUTE_MESSAGE
     *
     * @return the value of DDC_TASK.LAST_EXECUTE_MESSAGE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getLastExecuteMessage() {
        return lastExecuteMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.LAST_EXECUTE_MESSAGE
     *
     * @param lastExecuteMessage the value for DDC_TASK.LAST_EXECUTE_MESSAGE
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setLastExecuteMessage(String lastExecuteMessage) {
        this.lastExecuteMessage = lastExecuteMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.NEXT_FIRE_TIME
     *
     * @return the value of DDC_TASK.NEXT_FIRE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Date getNextFireTime() {
        return nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.NEXT_FIRE_TIME
     *
     * @param nextFireTime the value for DDC_TASK.NEXT_FIRE_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setNextFireTime(Date nextFireTime) {
        this.nextFireTime = nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.SIMPLE_START_TIME
     *
     * @return the value of DDC_TASK.SIMPLE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getSimpleStartTime() {
        return simpleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.SIMPLE_START_TIME
     *
     * @param simpleStartTime the value for DDC_TASK.SIMPLE_START_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setSimpleStartTime(String simpleStartTime) {
        this.simpleStartTime = simpleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.SIMPLE_END_TIME
     *
     * @return the value of DDC_TASK.SIMPLE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public String getSimpleEndTime() {
        return simpleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.SIMPLE_END_TIME
     *
     * @param simpleEndTime the value for DDC_TASK.SIMPLE_END_TIME
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setSimpleEndTime(String simpleEndTime) {
        this.simpleEndTime = simpleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.SIMPLE_REPEAT_COUNT
     *
     * @return the value of DDC_TASK.SIMPLE_REPEAT_COUNT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getSimpleRepeatCount() {
        return simpleRepeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.SIMPLE_REPEAT_COUNT
     *
     * @param simpleRepeatCount the value for DDC_TASK.SIMPLE_REPEAT_COUNT
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setSimpleRepeatCount(Integer simpleRepeatCount) {
        this.simpleRepeatCount = simpleRepeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DDC_TASK.SIMPLE_REPEAT_INTERVAL
     *
     * @return the value of DDC_TASK.SIMPLE_REPEAT_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public Integer getSimpleRepeatInterval() {
        return simpleRepeatInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DDC_TASK.SIMPLE_REPEAT_INTERVAL
     *
     * @param simpleRepeatInterval the value for DDC_TASK.SIMPLE_REPEAT_INTERVAL
     *
     * @mbggenerated Thu Aug 18 14:06:05 CST 2016
     */
    public void setSimpleRepeatInterval(Integer simpleRepeatInterval) {
        this.simpleRepeatInterval = simpleRepeatInterval;
    }
}