package com.iwellmass.dispatcher.admin.dao.model;

import java.util.Date;

public class DdcUserAlarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.USER_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.LOGIN_NAME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.APP_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.TASK_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.CREATE_USER
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddc_user_alarm.CREATE_TIME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.ID
     *
     * @return the value of ddc_user_alarm.ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.ID
     *
     * @param id the value for ddc_user_alarm.ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.USER_ID
     *
     * @return the value of ddc_user_alarm.USER_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.USER_ID
     *
     * @param userId the value for ddc_user_alarm.USER_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.LOGIN_NAME
     *
     * @return the value of ddc_user_alarm.LOGIN_NAME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.LOGIN_NAME
     *
     * @param loginName the value for ddc_user_alarm.LOGIN_NAME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.APP_ID
     *
     * @return the value of ddc_user_alarm.APP_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.APP_ID
     *
     * @param appId the value for ddc_user_alarm.APP_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.TASK_ID
     *
     * @return the value of ddc_user_alarm.TASK_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.TASK_ID
     *
     * @param taskId the value for ddc_user_alarm.TASK_ID
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.CREATE_USER
     *
     * @return the value of ddc_user_alarm.CREATE_USER
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.CREATE_USER
     *
     * @param createUser the value for ddc_user_alarm.CREATE_USER
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddc_user_alarm.CREATE_TIME
     *
     * @return the value of ddc_user_alarm.CREATE_TIME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddc_user_alarm.CREATE_TIME
     *
     * @param createTime the value for ddc_user_alarm.CREATE_TIME
     *
     * @mbggenerated Wed Jun 22 14:41:10 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}