server:
  port: 9306
spring:
  application:
    name: idc
  cloud:
    nacos:
      discovery:
        server-addr: nacos.iwellmass.com
      config:
        server-addr: nacos.iwellmass.com
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.iwellmass.com:3306/idc?characterEncoding=utf8&useSSL=false
    username: root
    password: zjhz2017

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false

mybatis:
  mapper-locations: /mapper/**
  type-aliases-package: com.iwellmass.idc.app.model
  type-handlers-packages: com.iwellmass.idc.app.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30


supervise:
  client:
    clientId: acme
    clientSecret: acmesecret
    autoApprove: true
    accessTokenValiditySeconds: 28800
    refreshTokenValiditySeconds: 57600

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
           -----END PUBLIC KEY-----
        id: openid
        serviceId: ${PREFIX:}resource
  user:
    password: password
  ignored: /**
  
feign:
  hystirx:
    enable: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        requestInterceptors:
        - com.iwellmass.auth.config.OAuth2FeignRequestInterceptor
        decode404: false

idc.scheduler.start-auto: true          # 是否开启调度
idc.scheduler.maxRunningJobs: 10       # 调度的最大并发数(nodeJob的最大运行数量)
idc.scheduler.openCallbackControl: false       # 是否开启回调监控功能，默认关闭
idc.scheduler.callbackTimeout: 7200  # 任务回调超时时间  单位:秒  默认2小时
idc.scheduler.retryCount: 3 # 单个任务失败后自动重试次数  默认重试3次

---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        namespace: dev

idc.scheduler.start-auto: true
idc.scheduler.callbackTimeout: 7200  # 测试callbackTimeout 为 2 * 60 * 60
idc.scheduler.openCallbackControl: false       # 是否开启回调监控功能，默认关闭
idc.scheduler.maxRunningJobs: 10  # 最大并发数，测试为10个
idc.scheduler.retryCount: 3 # 单个任务失败后自动重试次数  默认重试3次